### ISSUE TITLE
Extra closing curly brace

### ISSUE THREAD

**Issue by mslourens** [tomblachut/svelte-intellij#101]
When closing an {#if} {/if} the IDE inserts a closing curly brace after creating the first, and after entering the forward slash, a second closing curly brace is inserted. This way I always end up with an extra curly brace.

**Comment by tomblachut** [comment]
I'm aware of that. Should be fixed in #100

**Comment by mslourens** [comment]
When will you finish your PR? This bug is still rather annoying...

**Comment by tomblachut** [comment]
@mslourens I'm having trouble with broken formatter. Contributions welcome :)

**Comment by mslourens** [comment]
Sorry, I'm a front-end web developer, I have no experience with Java...

**Comment by jlefebure** [comment]
Where exactly do you need contributions and what do we have to do ? Maybe I can help
